# Generated by Django 5.1.1 on 2024-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='drow_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
