# Generated by Django 5.1.1 on 2024-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_bill_drow_status_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
